name: Birkan Icacan Test
favicon: null
layout_spectrum: 0.44633020902983844
typography_spectrum: 0.29885
title: Birkan Icacan Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0099ff'
    - '#ff6600'
    - '#ff0000'
    - '#ff4000'
    - '#ff5500'
  brandStrength: 0.6875
  lightness: 0.21171176875941455
  saturation: 0.8740262791980058
  rhythmicContrast: 0.06048638699576259
purpose: []
